version: 2.1
orbs:
  ruby: circleci/ruby@2.1.4 # https://circleci.com/orbs/registry/orb/circleci/ruby

jobs:
  build:
    docker:
      - image: cimg/ruby:3.3.5-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          RAILS_ENV: test
      - image: cimg/postgres:14.2
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: postgres
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Wait for DB
          command: 'dockerize -wait tcp://localhost:5432 -timeout 1m'
      - run:
          name: Set up database
          command: 'bundle exec rails db:create db:schema:load --trace'
      - ruby/rspec-test
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: Add git remote host to know hosts
          command: ssh-keyscan dokku.kevinbongart.net >> ~/.ssh/known_hosts
      - run:
          name: Add Dokku git remote
          command: git remote add dokku dokku@dokku.kevinbongart.net:ourbandiscalled
      - run:
          name: Deploy to Dokku
          command: git push dokku main

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
